name: Test
on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: A job to run solidity tests in js
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Environment Setup
        uses: actions/setup-node@v3
        with:
          node-version: 14.17.6
      - name: Run SUT Action
        uses: ioedeveloper/eth-ts-test@v0.12.16-dev
        with:
          test-path: 'test'
          contract-path: 'contracts'
          compiler-version: '0.7.6'